
set -a terminal-features "tmux-256color:RGB"
set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on   
set -g mode-keys vi
set -g status-justify absolute-centre
set -g status-position top
set -g status-style "bg=default fg=white"
set -g status-right '%m/%d %H:%M'
# set -g status-right ' #(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD)'
# set -g status-right ''
set -g status-left '#{pomodoro_status}'
set -g status-right-length 0
set -g status-left-length 100
setw -g window-status-current-style 'fg=colour0 bg=colour2 bold'
setw -g window-status-current-format ' #I: #W  '
setw -g mouse on

unbind r
bind r source-file ~/.config/tmux/tmux.conf
bind c new-window -c "#{pane_current_path}"

bind f new-window "tmux neww ~/.config/scripts/tmux-session-dispensary.sh"
bind L run "~/.config/scripts/tmux-session-dispensary.sh ~/documents/lollipoop"
bind N run "~/.config/scripts/tmux-session-dispensary.sh ~/documents/internetcollectiveness"
bind M run "~/.config/scripts/tmux-session-dispensary.sh ~/documents/METROPOL"
bind D run "~/.config/scripts/tmux-session-dispensary.sh ~/.config"
bind H run "~/.config/scripts/tmux-session-dispensary.sh ~"
bind g run "~/.config/scripts/open-github.sh"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

set -g @plugin 'olimorris/tmux-pomodoro-plus'
# set -g status-left "#{pomodoro_status}"

#  nitialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
